### ISSUE TITLE
ChainList

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/Beta1#4]
... maybe there are others as well.
shall we include already the Beta as testnet, even it will be short lived ?

https://chainlist.org/
https://github.com/DefiLlama/chainlist

**Comment by cryptonit** [comment]
guess we do that with release candidate which is expected beta2 and named as testnet

i dont think it make sence add a network with expected 3 months livetime

**Comment by SurfingNerd** [comment]
ok then i can close it.
